---
title: "fiddler-crab-sizes"
author: "Joe DeCesaro"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(kableExtra)
library(ggbeeswarm)
```

Data Read in
```{r, echo=FALSE}
body_sizes <- read_csv(here("data", "HTL-MAR-FiddlerCrabBodySize.csv"))
```

Our excellent plot
```{r, alt = "Crab carapace size increases with latitude in Eastern US salt marshes.", echo=FALSE}
ggplot(data = body_sizes, aes(x= Latitude, y= carapace_width)) +
  geom_jitter(aes(color = Latitude)) +
  labs(title = "Fiddler crab size by latitude", x = "Latitude (degrees)", y= "Carapace width (mm)", caption = "At higher latitudes, fiddler crabs have a higher carapace width due to Bergmann's rule.")
```

Lets make a table
```{r, echo=FALSE}
body_size_table <- body_sizes %>% 
  group_by(Site) %>% 
  summarize(Mean = round(mean(carapace_width), 2),
            Standard_Deviation = round(sd(carapace_width), 2),
            Sample_Size = n())

body_size_table %>% 
  kable(col.names = c("Site ID", "Mean Carapace 
                      Width (mm)", "Standard Deviation (mm)", "Sample Size"),
        caption = "Mean carapace width in mm, standard deviation (mm), and crab sample size at each site to test Bergmann's Rule.") %>% 
  kable_classic(full_width = FALSE)
```


Next plot

```{r, echo=FALSE, alt= "Bigger crabs live in colder water."}
body_sizes = body_sizes %>% 
  mutate(MATW_f = as_factor(MATW))

ggplot(data = body_sizes, aes(x= MATW_f, y= carapace_width)) +
  geom_beeswarm() +
  geom_boxplot(aes(MATW_f), alpha = 0.3, fill = "green") +
  theme_bw() +
  labs(title = "Fiddler crab carapace width by water temperature", x= "Mean Annual Water Temps (degrees C)", y= "Carapace width (mm)", caption = "Slight negative correlation between mean annual water temperature and carapace width.")
```

